# Generated by Django 3.0.4 on 2020-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonji_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramcustomer',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
