# Generated by Django 3.0.4 on 2020-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonji_bot', '0002_auto_20200407_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='telegramcustomer',
            name='first_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='telegramcustomer',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='telegramcustomer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telegramcustomer',
            name='username',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
