# Generated by Django 3.0.4 on 2020-03-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200331_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Customer'},
        ),
    ]
