# Generated by Django 3.0.4 on 2020-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200326_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='No Image', upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
