# Generated by Django 3.0.4 on 2020-03-31 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200331_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
